version: "3"
services:
    db:
        ports:
          - "#{sql_port}:1433"
        image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
        env_file: .env
        volumes:
            - #{sql_data_path}:/var/opt/mssql
    seq:
      image: datalust/seq:latest
      environment:
        - "ACCEPT_EULA=Y"
      volumes:
        - #{seq_data_path}:/data
      ports:
        - "#{seq_port}:80"
